#!name=Spotify去广告+听歌历史
#!desc=Spotify去广告加部分解锁会员功能,音质不能设置为超高;保留内置听歌历史记录
#!icon=https://img.icons8.com/?size=100&id=ZuQiaFCa1vXe&format=png&color=000000
#!date=260828


[Rule]
AND,((DOMAIN-SUFFIX, spotify.com), (PROTOCOL, QUIC)),REJECT
DOMAIN,aet.spotify.com,REJECT

[Header Rewrite]
http-request ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match

[URL Rewrite]

#屏蔽弹窗广告
^https:\/\/(spclient\.wg|.*-spclient)\.spotify\.com(:443)?\/pendragon - reject

# 屏蔽设置界面会员信息（仅影响展示）
^https:\/\/.*-spclient\.spotify\.com(:443)?\/pam-view-service\/ - reject

# 屏蔽 AI DJ
^https:\/\/.*37i9dQZF1EYkqdzj48dyYq - reject

[MITM]
hostname = %APPEND% spclient.wg.spotify.com, *spclient.spotify.com

[Script]
spotify-gabo = type=http-request,pattern=^https:\/\/(.*-spclient\.spotify\.com(:443)?|spclient\.wg\.spotify\.com)\/gabo-receiver-service,requires-body=0,script-path=https://raw.githubusercontent.com/TforThomas/spotify-noad-withstat/main/files/lpx/js/spot-gabo.js
spotify-proto-ev3 = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/TforThomas/spotify-noad-withstat/main/files/lpx/js/spot-proto-ev3.js,script-update-interval=0

#去广告
NoSearchAd = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/browsita\/v.\/browse,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/TforThomas/spotify-noad-withstat/main/files/lpx/js/spot-NoSearchAd.js
NoHomeAd = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/casita\/v.\/home\/default,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/TforThomas/spotify-noad-withstat/main/files/lpx/js/spot-NoHomeAd.js
NoScrollAd = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/scrollsita\/v.\/scroll\/spotify,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/TforThomas/spotify-noad-withstat/main/files/lpx/js/spot-NoScrollAd.js
